a=input("Enter the number you want to print table ")
print(f"Table of {a} is")
try:
 for i in range(1,11):
  print(f"{a} x {i}={int(a)*i}" )
except Exception as e:
  print("not done",e)
  

#to handle specific type of errror
try:
 b=int(input("Enter the number  "))
 a=[7,8]
 print(a[b])
 
except ValueError:
  print("enter statement is not a number",ValueError)
  
except IndexError:
  print("Index error")
    
finally:
  print("Done")  #finally keyword always executed , main usage is when try and catch is written in function block
  

 

try:
    c = int(input("Enter the number: "))
    if c > 10:  
        raise ValueError("Error occurred due to uncertain value") #raise keyword is used to prevent custom errors (which are generated by us)
except ValueError as e:
    print(e)
